variables:
  DOCKER_IMAGE_DRUPAL_BUILD: guillaumeduveau/build-drupal8
build:
  only:
    - staging
  image: $DOCKER_IMAGE_DRUPAL_BUILD
  script:
    - composer install --no-dev
  artifacts:
    paths:
    - ./
