version: "3.7"
services:
    php-ssl:
        build: ./docker/php-ssl
        depends_on:
            - db
        ports:
            - 8081:80
            - 8443:443
        volumes:
            - ./:/var/www/html
        links:
            - db
        restart: always
        networks:
            - php

    db:
        image: mysql:5.7
        env_file:
            - .env
        volumes:
            - ./mysql-datas:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - 33064:3306
        restart: always
        environment:
            - MYSQL_DATABASE:agrisudweb
            - MYSQL_USER:norsys2021
            - MYSQL_PASSWORD:MDP2NAF
            - MYSQL_ROOT_PASSWORD:MDP2NAF
        networks:
            - php
    gulp:
        build: ./docker/gulp
        volumes:
            - ./web/themes/custom/norsys_base:/home/node/app
            - ./web/themes/custom/norsys_base/package.json:/home/node/app/package.json
        networks:
            - php
networks:
    php:

volumes:
    data:
    mysql-datas:
