version: "3.7"
services:
    php-ssl:
        build:
            context: ./docker/
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8081:80
            - 8443:443
        volumes:
            - ./:/var/www/html
            - ./mysql-datas:/var/www/database
        links:
            - db
        restart: always
        networks:
            - php

    db:
        image: mysql:5.7
        env_file:
          - .env
        volumes:
            - ./mysql-datas:/var/lib/mysql
            - ./database:/docker-entrypoint-initdb.d
        ports:
            - 33064:3306
        restart: always
        environment:
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}!
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}!
        command:
            - --default-authentication-plugin=mysql_native_password
            - --max_allowed_packet=128M
            - --innodb_log_file_size=128M
            - --skip-grant-tables
        networks:
            - php

    gulp:
        build:
            context: ./web/themes/custom/norsys_base
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./web/themes/custom/norsys_base:/home/node/app
        networks:
            - php

networks:
    php:

volumes:
    data:
    mysql-datas:
