<?php

use Drupal\views\ViewExecutable;

/**
 * Implements hook_preprocess_page_title().
 */
function norsys_agrisud_preprocess_page_title(&$variables) {
  $fullArgs = \Drupal::request()->query->all();
  $taxonomyTerm = explode(':', $fullArgs['f'][0]);

  if (isset($taxonomyTerm[1])) {
    $term = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->load($taxonomyTerm[1]);
    $value = $term->name->value;
    $variables['title'] = t("Les " . $value);
  }
}

/**
 * Implements hook_views_pre_render().
 */
function norsys_agrisud_views_pre_render(&$view) {
  global $base_url;
  if ($view->id() == 'equipe' && ($view->current_display == 'block_2' || $view->current_display == 'block_3')) {
    foreach ($view->result as $i => $row) {
      //ksm($row->_entity->get('field_messagerie')->getValue());
      if($row->_entity->get('field_messagerie')->getValue()[0]['value']){
        $adress_mail = $row->_entity->get('field_messagerie')->getValue()[0]['value'];
        $messagerie =  t('<a href="mailto:'.$adress_mail.'"><img src="'.$base_url.'/themes/custom/norsys_base/images/messagerie.png" alt='.$adress_mail.' ></a>');
        $row->_entity->set('field_messagerie', $messagerie);

      }

    }
  }
}
